### ISSUE TITLE
causes a memory leak (10 mb/s)

### ISSUE THREAD

**Issue by PokusPollo** [maniek207/beepmusic#1]
piter fuckin fix your stuff you dingus

**Comment by maniek207** [comment]
buy more memory

**Comment by PokusPollo** [comment]
no u

**Comment by maniek207** [comment]
https://allegro.pl/oferta/pamiec-ram-hyperx-ddr4-16-gb-3200-10658770262?utm_feed=0bea3c3b-c234-4ed7-b135-655f9f70c134&utm_content=ps&utm_source=google&utm_medium=cpc&utm_campaign=_ELKTRK_PLA_Komputery+-+Wybrane+produkty+_PS_&ev_adgr=Komputery+-+PS&gclid=CjwKCAjw9aiIBhA1EiwAJ_GTSsuWH7AWimg9bYc-O4KLnk0V5DlqgpLWpYlZTVyqmQ50E1squKD7oRoCZ_gQAvD_BwE

**Comment by PokusPollo** [comment]
says with a gt 630 2gb vram brhuhuhuh

**Comment by maniek207** [comment]
says person with computer better than mine

**Comment by PokusPollo** [comment]
says the one who uses lesbian linux

**Comment by maniek207** [comment]
says the one who using arch

**Comment by PokusPollo** [comment]
says the one who doesnt have an irc channel

**Comment by maniek207** [comment]
says the one who don't have discord nitro

**Comment by PokusPollo** [comment]
says the one whos fursona is a banana

**Comment by maniek207** [comment]
says one who is animal

**Comment by PokusPollo** [comment]
says the one whoo... fuck i am out of ideas

**Comment by maniek207** [comment]
me too, whatever buy more memory there no memory leaks

**Comment by maniek207** [comment]
if you are not testing on 64 MB of RAM

**Comment by PokusPollo** [comment]
nah, tested with 4gb ram

**Comment by maniek207** [comment]
my computer have 4 GB ram and can run GTA V while running beepmusic

**Comment by PokusPollo** [comment]
does even gta run on a gt 630?

**Comment by maniek207** [comment]
yes at 40 fps at 800x600

**Comment by PokusPollo** [comment]
dayum, anyway fix it, im closing this issue

**Comment by maniek207** [comment]
Fixed

**Comment by rAiZeNXD** [comment]
wez se kurwa kup lepsza grafe ty jebany polaku
to nie jest kurwa 2012 ty czolku
